name: yasm_mobile
description: YASM Mobile App Code.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.3.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.1.0
  provider: ^6.0.1
  http: ^0.13.3
  json_annotation: ^4.4.0
  form_field_validator: ^1.1.0
  image_picker: ^0.8.2
  uuid: ^3.0.4
  cached_network_image: ^3.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  logger: ^1.1.0
  flutter_offline: ^2.0.0
  screenshot: ^1.2.3
  intl: ^0.17.0
  skeleton_loader: ^2.0.0+4
  firebase_messaging: ^11.2.5
  firebase_analytics: ^9.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.0.0
  json_serializable: ^6.1.3
  hive_generator: ^1.1.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/logo/
